const sidebarConfig = [
  'connect/docs/8x8-cpaas-products',
  {
    type: 'category',
    label: 'API Information',
    collapsed: true,
    items: [
      'connect/docs/getting-started',
      'connect/docs/api-rate-limiting',
      {
        type: 'category',
        label: 'Security',
        link: { type: 'doc', id: 'connect/docs/security-1' },
        collapsed: true,
        items: [
          'connect/docs/omnishield-overview',
          'connect/docs/recommendations-for-securing-your-traffic',
        ],
      },
      'connect/docs/webhook-migration-guide',
      'connect/docs/api-endpoint-migration-guide',
    ],
  },
  {
    type: 'category',
    label: 'SMS',
    collapsed: true,
    items: [
      'connect/docs/send-sms-api-reference',
      'connect/docs/tutorial-single-sms',
      'connect/docs/tutorial-batch-sms',
      'connect/docs/tutorial-mobile-verification',
      'connect/docs/tutorial-sms-engage',
      'connect/docs/tutorial-sms-feedback-api',
    ],
  },
  {
    type: 'category',
    label: 'Messaging Apps',
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'WhatsApp',
        link: { type: 'doc', id: 'connect/docs/whatsapp/whatsapp-hub' },
        collapsed: true,
        items: [
          'connect/docs/whatsapp/concepts-fundamentals',
          'connect/docs/whatsapp/getting-started',
          'connect/docs/whatsapp/message-types-templates',
          'connect/docs/whatsapp/whatsapp-in-8x8-connect',
          {
            type: 'category',
            label: 'WhatsApp over 8x8 API',
            link: { type: 'doc', id: 'connect/docs/whatsapp/whatsapp-over-8x8-api' },
            collapsed: true,
            items: [
              'connect/docs/whatsapp/template-components-reference',
              'connect/docs/whatsapp/template-message-api-library',
              'connect/docs/whatsapp/interactive-message-api-library',
              'connect/docs/whatsapp/whatsapp-webhooks',
              'connect/docs/whatsapp/whatsapp-media-hosting',
              'connect/docs/whatsapp/constructing-whatsapp-template-send-requests',
              'connect/docs/whatsapp/whatsapp-sms-fallback',
            ],
          },
          'connect/docs/whatsapp/advanced-capabilities',
          'connect/docs/whatsapp/scenarios-tutorials',
          'connect/docs/whatsapp/vertical-playbooks',
          'connect/docs/whatsapp/operations-monitoring',
          'connect/docs/whatsapp/governance-security',
          'connect/docs/whatsapp/reference-resources',
          'connect/docs/whatsapp/learning-paths',
          'connect/docs/guide-whatsapp-one-tap-or-zero-tap-authentication',
          'connect/docs/guide-whatsapp-template-validity-period-ttl',
        ],
      },
      {
        type: 'category',
        label: 'RCS',
        link: { type: 'doc', id: 'connect/docs/rcs/overview' },
        collapsed: true,
        items: [
          'connect/docs/rcs/registration',
          'connect/docs/rcs/message-types',
          'connect/docs/rcs/compliance',
          'connect/docs/rcs/billing',
        ],
      },
      'connect/docs/usage-samples-viber',
      'connect/docs/usage-samples-zns',
      'connect/docs/usage-samples-line-official-notification',
    ],
  },
  {
    type: 'category',
    label: 'Voice',
    collapsed: true,
    items: [
      'connect/docs/voice/overview',
      {
        type: 'category',
        label: 'WhatsApp Business Calling',
        collapsed: true,
        items: [
          'connect/docs/voice/whatsapp-business-calling/whatsapp-business-calling-overview',
          'connect/docs/voice/whatsapp-business-calling/whatsapp-business-calling-user-initiated',
          'connect/docs/voice/whatsapp-business-calling/whatsapp-business-calling-business-initiated',
          'connect/docs/voice/whatsapp-business-calling/whatsapp-business-calling-scenarios',
        ],
      },
      {
        type: 'category',
        label: 'Voice Messaging',
        collapsed: true,
        items: [
          'connect/docs/voice/voice-messaging/voice-messaging-guide',
          'connect/docs/voice/voice-messaging/session-status',
        ],
      },
      {
        type: 'category',
        label: 'IVR',
        collapsed: true,
        items: [
          'connect/docs/voice/ivr/ivr-introduction',
          'connect/docs/voice/ivr/simple-ivr',
          'connect/docs/voice/ivr/advanced-ivr',
          'connect/docs/voice/ivr/call-action-handling',
          'connect/docs/voice/ivr/webhook-setup-guide-for-ivr',
          'connect/docs/voice/ivr/session-summary-ivr',
        ],
      },
      {
        type: 'category',
        label: 'Number Masking',
        collapsed: true,
        items: [
          'connect/docs/voice/number-masking/getting-started-with-number-masking',
          'connect/docs/voice/number-masking/how-number-masking-protects-customer-privacy',
          'connect/docs/voice/number-masking/call-action-handling',
          'connect/docs/voice/number-masking/session-summary-number-masking',
          'connect/docs/voice/number-masking/number-masking-call-status',
          'connect/docs/voice/number-masking/number-masking-call-recordings',
          'connect/docs/voice/number-masking/virtual-number-updated',
        ],
      },
      {
        type: 'category',
        label: 'Voice SDK',
        collapsed: true,
        items: [
          'connect/docs/voice/voice-sdk/voice-sdk-overview',
          {
            type: 'category',
            label: 'Android - Integrating the SDK',
            link: { type: 'doc', id: 'connect/docs/voice/voice-sdk/voice-sdk-android-integrating' },
            collapsed: true,
            items: [
              'connect/docs/voice/voice-sdk/voice-sdk-using',
              'connect/docs/voice/voice-sdk/voice-sdk-api-specification-android',
            ],
          },
          {
            type: 'category',
            label: 'iOS - Integrating the SDK',
            link: { type: 'doc', id: 'connect/docs/voice/voice-sdk/voice-sdk-ios-integrating' },
            collapsed: true,
            items: [
              'connect/docs/voice/voice-sdk/voice-sdk-using-ios',
              'connect/docs/voice/voice-sdk/voice-sdk-api-specification-ios',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'Webhooks',
        collapsed: true,
        items: [
          'connect/docs/voice/webhook-guides/webhooks-overview',
          'connect/docs/voice/webhook-guides/voice-call-action-webhook-guide',
          'connect/docs/voice/webhook-guides/voice-session-summary-webhook',
          'connect/docs/voice/voice-messaging/session-status',
          'connect/docs/voice/ivr/session-summary-ivr',
        ],
      },
      {
        type: 'category',
        label: 'Status and Error Codes Guide',
        collapsed: true,
        items: [
          'connect/docs/voice/error-codes/voice-status-codes',
          'connect/docs/voice/error-codes/voice-error-codes',
          'connect/docs/voice/error-codes/number-masking-error-codes',
        ],
      },
      {
        type: 'category',
        label: 'General Voice API Information',
        collapsed: true,
        items: [
          'connect/docs/voice/voice-ip-addresses',
        ],
      },
    ],
  },  

  {
    type: 'category',
    label: 'Connect Portal',
    collapsed: true,
    items: [
      'connect/docs/connect-overview',
      {
        type: 'category',
        label: 'Multi-channel Sender',
        link: { type: 'doc', id: 'connect/docs/sender' },
        collapsed: true,
        items: [
          'connect/docs/sending-sms-using-mcs',
          'connect/docs/sending-chat-apps-using-mcs',
        ],
      },
      {
        type: 'category',
        label: 'Sender ID Self Registration',
        link: {
          type: 'doc',
          id: 'connect/docs/sender-id-self-registration-module',
        },
        collapsed: true,
        items: [
          {
            type: 'category',
            label: 'Sender ID Dashboard',
            link: { type: 'doc', id: 'connect/docs/sender-id-dashboard' },
            collapsed: true,
            items: [
              'connect/docs/sender-id-dashboard-view',
              'connect/docs/drafts',
            ],
          },
          {
            type: 'category',
            label: 'Documents & Details Dashboard',
            link: {
              type: 'doc',
              id: 'connect/docs/documents-details-dashboard',
            },
            collapsed: true,
            items: ['connect/docs/company-details-tab'],
          },
          {
            type: 'category',
            label: 'Registration Module',
            link: { type: 'doc', id: 'connect/docs/registration-module' },
            collapsed: true,
            items: [
              'connect/docs/details',
              'connect/docs/documents',
              'connect/docs/adding-sender-id-details',
              'connect/docs/reviewing-submission',
              'connect/docs/submitter-sender-id-registrations',
              'connect/docs/signing-loa',
            ],
          },
        ],
      },
      {
        type: 'doc',
        id: 'connect/docs/verif8',
        label: 'Verif8',
      },
      {
        type: 'category',
        label: 'Analytics',
        link: { type: 'doc', id: 'connect/docs/analytics' },
        collapsed: true,
        items: [
          'connect/docs/sms-analytics',
          'connect/docs/messaging-apps',
          'connect/docs/video-interaction-analytics',
        ],
      },
      'connect/docs/contact-management',
      {
        type: 'category',
        label: 'Templates',
        link: { type: 'doc', id: 'connect/docs/templates' },
        collapsed: true,
        items: [
          'connect/docs/template-management',
          'connect/docs/whatsapp-templates-management',
        ],
      },
      {
        type: 'category',
        label: 'Automation Builder',
        link: { type: 'doc', id: 'connect/docs/automation-builder' },
        collapsed: true,
        items: [
          'connect/docs/triggers-and-steps-library',
          'connect/docs/triggers',
          'connect/docs/troubleshooting',
          'connect/docs/tutorial-add-an-opt-out-keyword-sms',
          'connect/docs/tutorial-add-an-opt-out-keyword-whatsapp',
          'connect/docs/tutorial-opt-out-keyword-sms-for-third-party-system',
          'connect/docs/tutorial-opt-out-keyword-messaging-apps-whatsapp-for-third-party-system',
          'connect/docs/tutorial-automation-builder-sms-chatapps-reservation-menu',
          'connect/docs/tutorial-building-a-whatsapp-google-calendar-chat-bot',
          'connect/docs/tutorial-customer-survey-via-sms',
          'connect/docs/tutorial-whatsapp-survey',
        ],
      },
      'connect/docs/user-management',
      'connect/docs/connect-security',
      'connect/docs/authentication',
      'connect/docs/developer-tools',
      'connect/docs/data-center-region',
    ],
  },
  {
    type: 'category',
    label: 'Contacts API Tutorials',
    collapsed: true,
    items: [
      'connect/docs/creating-a-contact',
      'connect/docs/create-a-group-and-add-a-contact-to-that-group',
    ],
  },
  {
    type: 'category',
    label: 'Integrations',
    collapsed: true,
    items: [
      'connect/docs/adobe-campaigns',
      'connect/docs/apples-shortcuts',
      'connect/docs/auth0',
      'connect/docs/braze',
      {
        type: 'category',
        label: 'CleverTap',
        link: { type: 'doc', id: 'connect/docs/clevertap' },
        collapsed: true,
        items: [
          'connect/docs/clevertap-sms-integration',
          'connect/docs/clevertap-whatsapp-integration',
        ],
      },
      'connect/docs/cognigy',
      {
        type: 'doc',
        id: 'connect/docs/detrack',
        label: 'Detrack - SMS Integration',
      },
      'connect/docs/integrations-overview',
      'connect/docs/freshdesk',
      {
        type: 'category',
        label: 'Make.com',
        link: { type: 'doc', id: 'connect/docs/makecom-1' },
        collapsed: true,
        items: ['connect/docs/make'],
      },
      {
        type: 'category',
        label: 'MoEngage',
        link: { type: 'doc', id: 'connect/docs/moengage' },
        collapsed: true,
        items: [
          'connect/docs/moengage-sms-integration',
          'connect/docs/moengage-whatsapp',
        ],
      },
      'connect/docs/oracle-responsys',
      {
        type: 'category',
        label: 'Okta - Bring Your Own Telephony (BYOT)',
        link: {
          type: 'doc',
          id: 'connect/docs/okta-bring-your-own-telephony-byot',
        },
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'connect/docs/okta',
            label: 'Okta - Bring Your Own Telephony (BYOT) via SMS',
          },
          {
            type: 'doc',
            id: 'connect/docs/okta-bring-your-own-telephony-byot-via-voice-otp',
            label: 'Okta - Bring Your Own Telephony (BYOT) via Voice',
          },
        ],
      },
      'connect/docs/salesforce-live-agent',
      {
        type: 'category',
        label: 'Salesforce Flow Builder',
        link: { type: 'doc', id: 'connect/docs/salesforce-flow-builder' },
        collapsed: true,
        items: [
          'connect/docs/salesforce-flowbuilder-8x8-messaging-integration',
          'connect/docs/salesforce-flowbuilder-8x8-sms-integration',
        ],
      },
      'connect/docs/workato',
      {
        type: 'category',
        label: 'Zapier',
        link: { type: 'doc', id: 'connect/docs/zapier' },
        collapsed: true,
        items: ['connect/docs/zapier-google-sheets-and-sms'],
      },
      'connect/docs/zendesk-support',
      'connect/docs/zendesk-notifications-webhooks',
    ],
  },
  {
    type: 'category',
    label: 'Converse',
    collapsed: true,
    items: [
      'connect/docs/converse-overview',
      'connect/docs/dashboard',
      {
        type: 'category',
        label: 'My Conversations',
        link: { type: 'doc', id: 'connect/docs/my-conversations' },
        collapsed: true,
        items: [
          'connect/docs/ticket-queue-logic',
          'connect/docs/ticket-management',
        ],
      },
      'connect/docs/all-conversations',
      'connect/docs/configuration',
      'connect/docs/agent-management',
      {
        type: 'category',
        label: 'Advanced Queueing',
        link: {
          type: 'doc',
          id: 'connect/docs/agent-queueing-advanced-queueing',
        },
        collapsed: true,
        items: [
          'connect/docs/channel-based-queueing',
          'connect/docs/country-based-queueing',
          'connect/docs/customer-group-based-queueing',
          'connect/docs/combining-different-queue-conditions',
          'connect/docs/advanced-queueing-tutorial',
        ],
      },
    ],
  },
  {
    type: 'category',
    label: 'Video Interaction',
    collapsed: true,
    items: [
      'connect/docs/vi-overview',
      'connect/docs/vi-agent-interface',
      'connect/docs/vi-customer-interface',
      'connect/docs/vi-administrator-interface',
      'connect/docs/vi-network-requirements',
      'connect/docs/vi-frequently-asked-questions',
    ],
  },
  {
    type: 'category',
    label: 'Partner Hub',
    collapsed: true,
    items: [
      'connect/docs/accessing-and-viewing-your-customer-list',
      'connect/docs/for-partner-admins-managing-your-team',
    ],
  },
];

module.exports = sidebarConfig;
