const sidebarConfig = [
  {
    type: 'category',
    label: 'API Information',
    collapsed: true,
    items: [
      'connect/docs/getting-started',
      'connect/docs/api-rate-limiting',
      {
        type: 'category',
        label: 'Security',
        link: { type: 'doc', id: 'connect/docs/security-1' },
        collapsed: true,
        items: [
          'connect/docs/omnishield-overview',
          'connect/docs/recommendations-for-securing-your-traffic',
        ],
      },
      'connect/docs/webhook-migration-guide',
      'connect/docs/api-endpoint-migration-guide',
    ],
  },
  {
    type: 'category',
    label: 'SMS',
    collapsed: true,
    items: [
      'connect/docs/send-sms-api-reference',
      'connect/docs/tutorial-single-sms',
      'connect/docs/tutorial-batch-sms',
      'connect/docs/tutorial-mobile-verification',
      'connect/docs/tutorial-sms-engage',
      'connect/docs/tutorial-sms-feedback-api',
    ],
  },
  {
    type: 'category',
    label: 'Messaging Apps',
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'WhatsApp',
        collapsed: true,
        items: [
          'connect/docs/usage-samples-whatsapp',
          'connect/docs/guide-creating-whatsapp-template-request',
          'connect/docs/guide-whatsapp-one-tap-or-zero-tap-authentication',
          'connect/docs/guide-whatsapp-template-validity-period-ttl',
          'connect/docs/guide-whatsapp-image-optimization',
        ],
      },
      {
        type: 'category',
        label: 'RCS',
        link: { type: 'doc', id: 'connect/docs/guide-rcs' },
        collapsed: true,
        items: [
          'connect/docs/getting-started-1',
          'connect/docs/compliance',
          'connect/docs/usage-samples-rcs',
          'connect/docs/billing',
        ],
      },
      'connect/docs/usage-samples-viber',
      'connect/docs/usage-samples-zns',
      'connect/docs/usage-samples-line-official-notification',
    ],
  },
  {
    type: 'category',
    label: 'Connect Portal',
    collapsed: true,
    items: [
      'connect/docs/connect-overview',
      {
        type: 'category',
        label: 'Multi-channel Sender',
        link: { type: 'doc', id: 'connect/docs/sender' },
        collapsed: true,
        items: [
          'connect/docs/sending-sms-using-mcs',
          'connect/docs/sending-chat-apps-using-mcs',
        ],
      },
      {
        type: 'category',
        label: 'Sender ID Self Registration',
        link: {
          type: 'doc',
          id: 'connect/docs/sender-id-self-registration-module',
        },
        collapsed: true,
        items: [
          {
            type: 'category',
            label: 'Sender ID Dashboard',
            link: { type: 'doc', id: 'connect/docs/sender-id-dashboard' },
            collapsed: true,
            items: [
              'connect/docs/sender-id-dashboard-view',
              'connect/docs/drafts',
            ],
          },
          {
            type: 'category',
            label: 'Documents & Details Dashboard',
            link: {
              type: 'doc',
              id: 'connect/docs/documents-details-dashboard',
            },
            collapsed: true,
            items: ['connect/docs/company-details-tab'],
          },
          {
            type: 'category',
            label: 'Registration Module',
            link: { type: 'doc', id: 'connect/docs/registration-module' },
            collapsed: true,
            items: [
              'connect/docs/details',
              'connect/docs/documents',
              'connect/docs/adding-sender-id-details',
              'connect/docs/reviewing-submission',
              'connect/docs/submitter-sender-id-registrations',
              'connect/docs/signing-loa',
            ],
          },
        ],
      },
      {
        type: 'doc',
        id: 'connect/docs/verif8',
        label: 'Verif8',
      },
      {
        type: 'category',
        label: 'Analytics',
        link: { type: 'doc', id: 'connect/docs/analytics' },
        collapsed: true,
        items: [
          'connect/docs/sms-analytics',
          'connect/docs/messaging-apps',
          'connect/docs/video-interaction-analytics',
        ],
      },
      'connect/docs/contact-management',
      {
        type: 'category',
        label: 'Templates',
        link: { type: 'doc', id: 'connect/docs/templates' },
        collapsed: true,
        items: [
          'connect/docs/template-management',
          'connect/docs/whatsapp-templates-management',
        ],
      },
      {
        type: 'category',
        label: 'Automation Builder',
        link: { type: 'doc', id: 'connect/docs/automation-builder' },
        collapsed: true,
        items: [
          'connect/docs/triggers-and-steps-library',
          'connect/docs/triggers',
          'connect/docs/troubleshooting',
          'connect/docs/tutorial-add-an-opt-out-keyword-sms',
          'connect/docs/tutorial-add-an-opt-out-keyword-whatsapp',
          'connect/docs/tutorial-opt-out-keyword-sms-for-third-party-system',
          'connect/docs/tutorial-opt-out-keyword-messaging-apps-whatsapp-for-third-party-system',
          'connect/docs/tutorial-automation-builder-sms-chatapps-reservation-menu',
          'connect/docs/tutorial-building-a-whatsapp-google-calendar-chat-bot',
          'connect/docs/tutorial-customer-survey-via-sms',
          'connect/docs/tutorial-whatsapp-survey',
        ],
      },
      'connect/docs/user-management',
      'connect/docs/connect-security',
      'connect/docs/authentication',
      'connect/docs/developer-tools',
      'connect/docs/data-center-region',
    ],
  },
  {
    type: 'category',
    label: 'Contacts API Tutorials',
    collapsed: true,
    items: [
      'connect/docs/creating-a-contact',
      'connect/docs/create-a-group-and-add-a-contact-to-that-group',
    ],
  },
  {
    type: 'category',
    label: 'Integrations',
    collapsed: true,
    items: [
      'connect/docs/adobe-campaigns',
      'connect/docs/apples-shortcuts',
      'connect/docs/auth0',
      'connect/docs/braze',
      {
        type: 'category',
        label: 'CleverTap',
        link: { type: 'doc', id: 'connect/docs/clevertap' },
        collapsed: true,
        items: [
          'connect/docs/clevertap-sms-integration',
          'connect/docs/clevertap-whatsapp-integration',
        ],
      },
      'connect/docs/cognigy',
      {
        type: 'doc',
        id: 'connect/docs/detrack',
        label: 'Detrack - SMS Integration',
      },
      'connect/docs/integrations-overview',
      'connect/docs/freshdesk',
      {
        type: 'category',
        label: 'Make.com',
        link: { type: 'doc', id: 'connect/docs/makecom-1' },
        collapsed: true,
        items: ['connect/docs/make'],
      },
      {
        type: 'category',
        label: 'MoEngage',
        link: { type: 'doc', id: 'connect/docs/moengage' },
        collapsed: true,
        items: [
          'connect/docs/moengage-sms-integration',
          'connect/docs/moengage-whatsapp',
        ],
      },
      'connect/docs/oracle-responsys',
      {
        type: 'category',
        label: 'Okta - Bring Your Own Telephony (BYOT)',
        link: { type: 'doc', id: 'connect/docs/okta' },
        collapsed: true,
        items: [],
      },
      'connect/docs/salesforce-live-agent',
      {
        type: 'category',
        label: 'Salesforce Flow Builder',
        link: { type: 'doc', id: 'connect/docs/salesforce-flow-builder' },
        collapsed: true,
        items: [
          'connect/docs/salesforce-flowbuilder-8x8-messaging-integration',
          'connect/docs/salesforce-flowbuilder-8x8-sms-integration',
        ],
      },
      'connect/docs/workato',
      {
        type: 'category',
        label: 'Zapier',
        link: { type: 'doc', id: 'connect/docs/zapier' },
        collapsed: true,
        items: ['connect/docs/zapier-google-sheets-and-sms'],
      },
      'connect/docs/zendesk-support',
      'connect/docs/zendesk-notifications-webhooks',
    ],
  },
  {
    type: 'category',
    label: 'Voice SDK',
    collapsed: true,
    items: [
      'connect/docs/overview',
      {
        type: 'category',
        label: 'Android - Integrating the SDK',
        link: { type: 'doc', id: 'connect/docs/android-integrating-the-sdk' },
        collapsed: true,
        items: [
          'connect/docs/using-the-sdk',
          'connect/docs/api-specification-android',
        ],
      },
      {
        type: 'category',
        label: 'iOS - Integrating the SDK',
        link: { type: 'doc', id: 'connect/docs/ios-integrating-the-sdk' },
        collapsed: true,
        items: [
          'connect/docs/using-the-ios-sdk',
          'connect/docs/api-specification-ios',
        ],
      },
    ],
  },
  {
    type: 'category',
    label: 'Converse',
    collapsed: true,
    items: [
      'connect/docs/converse-overview',
      'connect/docs/dashboard',
      {
        type: 'category',
        label: 'My Conversations',
        link: { type: 'doc', id: 'connect/docs/my-conversations' },
        collapsed: true,
        items: [
          'connect/docs/ticket-queue-logic',
          'connect/docs/ticket-management',
        ],
      },
      'connect/docs/all-conversations',
      'connect/docs/configuration',
      'connect/docs/agent-management',
      {
        type: 'category',
        label: 'Advanced Queueing',
        link: {
          type: 'doc',
          id: 'connect/docs/agent-queueing-advanced-queueing',
        },
        collapsed: true,
        items: [
          'connect/docs/channel-based-queueing',
          'connect/docs/country-based-queueing',
          'connect/docs/customer-group-based-queueing',
          'connect/docs/combining-different-queue-conditions',
          'connect/docs/advanced-queueing-tutorial',
        ],
      },
    ],
  },
  {
    type: 'category',
    label: 'Video Interaction',
    collapsed: true,
    items: [
      'connect/docs/vi-overview',
      'connect/docs/vi-agent-interface',
      'connect/docs/vi-customer-interface',
      'connect/docs/vi-administrator-interface',
      'connect/docs/vi-network-requirements',
      'connect/docs/vi-frequently-asked-questions',
    ],
  },
  {
    type: 'category',
    label: 'Partner Hub',
    collapsed: true,
    items: [
      'connect/docs/accessing-and-viewing-your-customer-list',
      'connect/docs/for-partner-admins-managing-your-team',
    ],
  },
];

module.exports = sidebarConfig;
