const sidebarConfig = [
  {
    type: 'category',
    label: 'Getting Started',
    collapsed: true,
    items: ['jaas/docs/jaas-onboarding'],
  },
  {
    type: 'category',
    label: 'FAQ',
    collapsed: true,
    items: ['jaas/docs/faq'],
  },
  {
    type: 'category',
    label: 'API keys',
    collapsed: true,
    items: [
      'jaas/docs/api-keys-overview',
      'jaas/docs/api-keys-generate-add',
      'jaas/docs/api-keys-jwt',
      'jaas/docs/api-key-backend',
    ],
  },
  {
    type: 'category',
    label: 'Jitsi IFrame API',
    collapsed: true,
    items: [
      'jaas/docs/iframe-api-overview',
      'jaas/docs/iframe-api-integration',
      'jaas/docs/iframe-api-functions',
      'jaas/docs/iframe-api-commands',
      'jaas/docs/iframe-api-events',
      'jaas/docs/iframe-api-invite',
      'jaas/docs/jaas-browser-support',
    ],
  },
  {
    type: 'category',
    label: 'Customize the UI',
    collapsed: true,
    items: [
      'jaas/docs/customize-ui-overview',
      'jaas/docs/customize-ui-default-language',
      'jaas/docs/customize-ui-buttons',
      'jaas/docs/custom-buttons-iframe-api',
    ],
  },
  {
    type: 'category',
    label: 'JaaS Preferences and Meeting Features',
    collapsed: true,
    items: [
      'jaas/docs/jaas-prefs-overview',
      'jaas/docs/jaas-prefs-devices',
      'jaas/docs/jaas-prefs-prejoin',
      'jaas/docs/jaas-prefs-security',
      'jaas/docs/jaas-prefs-recording',
      'jaas/docs/jaas-prefs-advanced-branding',
      'jaas/docs/whiteboard',
      'jaas/docs/pstn-dial-in-and-out',
      'jaas/docs/sip-dial-in-and-out',
      'jaas/docs/transcription-translation',
      'jaas/docs/livestreaming',
    ],
  },
  {
    type: 'category',
    label: 'Mobile SDKs',
    collapsed: true,
    items: [
      'jaas/docs/mobile-sdk-overview',
      'jaas/docs/mobile-sdk-android',
      'jaas/docs/mobile-sdk-ios',
    ],
  },
  {
    type: 'category',
    label: 'Web SDKs',
    collapsed: true,
    items: ['jaas/docs/web-sdk-overview', 'jaas/docs/web-sdk-react'],
  },
  {
    type: 'category',
    label: 'Webhooks',
    collapsed: true,
    items: [
      'jaas/docs/webhooks-overview',
      'jaas/docs/webhooks-events',
      'jaas/docs/webhooks-payload',
      'jaas/docs/webhooks-signatures',
      'jaas/docs/webhooks-jaas-endpoints',
    ],
  },
  {
    type: 'category',
    label: 'The JaaS console',
    collapsed: true,
    items: [
      'jaas/docs/jaas-console-overview',
      'jaas/docs/jaas-console-my-sample-app',
      'jaas/docs/jaas-console-activity',
      'jaas/docs/jaas-console-api-keys',
      'jaas/docs/jaas-console-webhooks',
      'jaas/docs/jaas-console-branding',
      'jaas/docs/releases',
      'jaas/docs/ai-services',
      'jaas/docs/jaas-console-team-management',
      'jaas/docs/jaas-console-plans-and-subscriptions',
      'jaas/docs/jaas-console-billing',
      'jaas/docs/jaas-console-start-guide',
      'jaas/docs/jaas-console-help-and-docs',
      'jaas/docs/jaas-console-contact-support',
    ],
  },
  {
    type: 'category',
    label: 'JAAS ANALYTICS',
    collapsed: true,
    items: [
      'jaas/docs/jaas-console-analytics',
      'jaas/docs/rtc-visualizer',
      'jaas/docs/jaas-statistics-file',
      'jaas/docs/enabling-with-lib-jitsi-meet-sdk',
    ],
  },
  {
    type: 'category',
    label: 'Jitsi Meet Components',
    collapsed: true,
    items: [
      'jaas/docs/meet-components-overview',
      'jaas/docs/meet-components-telephony-access',
      'jaas/docs/meet-components-telephony-access-docker',
      'jaas/docs/meet-components-telephony-access-debian',
      'jaas/docs/meet-components-telephony-access-manual-install',
    ],
  },
  {
    type: 'category',
    label: 'Whitelisting',
    collapsed: true,
    items: ['jaas/docs/technical-requirements-whitelists'],
  },
  {
    type: 'category',
    label: 'Release Notes',
    collapsed: true,
    items: [
      'jaas/docs/mobile-sdk-release-notes',
      'jaas/docs/release-6176',
      'jaas/docs/release-5963',
      'jaas/docs/release-5821',
      'jaas/docs/release-5628',
      'jaas/docs/release-5518',
      'jaas/docs/release-5327',
      'jaas/docs/release-5218',
      'jaas/docs/release-5082',
      'jaas/docs/release-4953',
      'jaas/docs/release-4871',
      'jaas/docs/release-4620',
      'jaas/docs/release-4546',
      'jaas/docs/release-4429',
      'jaas/docs/release-4340',
      'jaas/docs/release-4245',
      'jaas/docs/release-4150',
      'jaas/docs/release-3958',
      'jaas/docs/release-3792',
      'jaas/docs/release-3704',
      'jaas/docs/release-3636',
      'jaas/docs/release-3527',
      'jaas/docs/release-3315',
      'jaas/docs/release-3192',
      'jaas/docs/release-3118',
      'jaas/docs/release-2995',
      'jaas/docs/24-february-2022-release',
      'jaas/docs/20-january-2022-release',
      'jaas/docs/16-december-2021-release',
      'jaas/docs/14-december-2021-release',
      'jaas/docs/16-november-2021-release',
      'jaas/docs/14-october-2021-release',
      'jaas/docs/23-september-2021-release',
      'jaas/docs/15-september-2021-release',
      'jaas/docs/9-september-2021-release',
      'jaas/docs/27-august-2021-release',
      'jaas/docs/27-july-2021-release',
      'jaas/docs/16-july-2021-release',
      'jaas/docs/24-june-2021-release',
      'jaas/docs/22-june-2021-release',
    ],
  },
];

module.exports = sidebarConfig;
